### ISSUE TITLE
Supported barcode readers

### ISSUE THREAD

**Issue by miderose** [goodeggs/angular-barcode-listener#10]
Hi! Is there a list of supported readers?

**Comment by serhalp** [comment]
Hi @miderose. Nope – this should work with any barcode scanner in "keyboard wedge" mode, i.e. which is acting as a keyboard and "typing in" the barcode one keypress at a time in quick succession. As long as it takes less than [`scanDuration`](https://github.com/goodeggs/angular-barcode-listener#configuration) (which defaults to 50 ms) it should detect it.
