### ISSUE TITLE
Update npmjs latest version

### ISSUE THREAD

**Issue by n1c** [goodeggs/angular-barcode-listener#6]
The latest version listed on npmjs.com is [1.1.0](https://www.npmjs.com/package/angular-barcode-listener) while there's a release for 1.5.0 here.

**Comment by serhalp** [comment]
Hi @n1c, thanks for reporting!  It looks like we've been accidentally publishing this module to our private registry for quite some time.  I've just published the latest as `1.5.1` to npmjs.

**Comment by n1c** [comment]
No problem 👍
